// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTableNamesFromModels() {
  return window['go']['main']['App']['GetTableNamesFromModels']();
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function RecreateTables() {
  return window['go']['main']['App']['RecreateTables']();
}
