// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetTableNamesFromModels():Promise<main.TablesListResponse>;

export function GetTableSchema(arg1:string):Promise<Array<main.FieldSchema>>;

export function RecreateTables():Promise<main.RecreateTablesResult>;
